version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "always"
    container_name: "client"
    ports:
      - "3000:3000"
    volumes:
      - ./:/client
      - /client/node_modules
      - /client/.next